### ISSUE TITLE
Strange behavior with nested cfgselect components

### ISSUE THREAD

**Issue by kjellwinblad** [emqx/emqx-dashboard-web#378]
I have created a resource config with nested cfgselect components.

See:

https://github.com/kjellwinblad/emqx-enterprise/blob/df15d2a95e42a74fd81ef3806a696bcf77d5ef76/lib-ee/emqx_rule_actions/src/emqx_bridge_kafka_actions.erl#L153-L219

Unfortunately, this does not work as I had expected. When setting the cfgselect on the first level I would have expected to see two more fields (one for Kerberos Principal and one for the cfgselect on the second level). Instead I just see one new component, the "Kerberos Keytab 2" field (see screenshot below).

Is this a bug or is there something wrong with my configuration?

Edit: I am using emqx-enterprise 4.4 and the `dev/4.4` branch of this repository.

![pic-full-220630-1726-21](https://user-images.githubusercontent.com/200374/176716301-8d1c7606-93ab-46f6-8f97-43939aaf59d6.png)

**Comment by Kinplemelon** [comment]
I will fix it, thank you for your issue!

**Comment by Kinplemelon** [comment]
Fixed it, please use the dev/4.4 branch to check.😄

**Comment by kjellwinblad** [comment]
I can confirm that this is fixed now. Can you publish a new release that includes the three fixes you have done for me and send the release name/version for the new release, so that I can update emqx-enterprise 4.4 to download the new version of the dashboard?

**Comment by Kinplemelon** [comment]
Sorry, I may have to release a bit later, as 4.4 has some other bugfixes to commit. If you need to test locally, can you manually replace the dashboard package first?

**Comment by Kinplemelon** [comment]
I will close this issue

**Comment by kjellwinblad** [comment]
Yes, I can test using the dev/4.4 branch. Thanks! Please let me know when the release is made so that I know that my changes in EMQX enterprise 4.4 can be release.

**Comment by Kinplemelon** [comment]
okay!

**Comment by kjellwinblad** [comment]
@Kinplemelon can you make a comment on PR https://github.com/emqx/emqx-enterprise/pull/1119 when a new release including these fixes have been published. I'm reopening this issue just to make sure you see this message. You can close it again once you have seen it.

**Comment by Kinplemelon** [comment]
Of course, I will not close this issue until a new package is released.
